version: '3.9'
services:
  btcd:
    container_name: btcd
    hostname: btcd
    build: https://github.com/btcsuite/btcd.git#master
    restart: unless-stopped
    volumes:
      - btcd-data:/root/.btcd
    ports:
      - 18444:18444
    command: [ "--regtest" ]

volumes:
  btcd-data:
